
#General
[general]
	#The chance for an item to add a level of compost
	#Range: 0.10000000149011612 ~ 1.0
	upcycle_chance = 0.30000001192092896
	#Enables ingame rewards on first spawn for Patreons
	patreon_rewards = true

