
["TPA++ Messages"]
	# Don't know how Minecrafts §<color code> formatting works? Check out: https://www.digminecraft.com/lists/color_list_pc.php
	# Due to the nature of now Strings are immutable in java, all values in this configuration require a restart to take affect!
	# ALL MESSAGES SUPPORT JAVA SYNTAX FORMATTING! If you say want to put a newline into the message, just enter \n, or if you want to add double quotes into a message enter "\"
	#
	# The message for when your teleport request could not be found.
	ERR_REQUEST_NOT_FOUND = "§cCould not find your teleport request!"
	#
	# The message for when a player attempts to use /tpa or /tpahere on themselves
	ERR_NO_SELF_TELEPORT = "§cYou can't send a teleport request to yourself!"
	#
	# The message that is sent to the sender of a TPA request, when they have already sent a teleport request to that player.
	# Placeholders: "${receiver_name}": "The name of the receiver you tried to send a teleport request to"
	ALREADY_SENT_TELEPORT_REQUEST = "§cYou already sent ${receiver_name} a TPA request!"
	#
	# The message sent to the sender of a TPA request when the receiver has /tptoggle on, preventing all outside teleport requests
	# Placeholders: "${receiverName}": "The name of the receiver that they are trying to teleport to."
	ERR_RECEIVER_TP_DISABLED = "§c${receiverName} has disabled outside teleport requests!"
	#
	# The message sent to the sender of a TPA request when the sender (themselves) has /tptoggle on, preventing all outside teleport requests
	# This has no affect if this is disabled in the config
	ERR_SENDER_TP_DISABLED = "§cYou have disabled outside teleport requests!"
	#
	# The message that is sent to the sender of a TPA request when the sender (themselves) has blocked the recipient
	# Placeholders: "${blocked_player}": "The name of the player who has been blocked by the sender"
	SENDER_BLOCKED_RECEIVER = "§6You have §cblocked ${blocked_player}§6!"
	#
	# The message that is sent to the sender of a TPA request, when the receiver has blocked the sender
	# Placeholders: "${blocking_player}": "The name of the player who has blocked the sender"
	RECEIVER_BLOCKED_SENDER = "§c${blocking_player} §6has §cblocked §6you!"

	["TPA++ Messages"."/back"]
		#
		# The message for when /back has been disabled in the servers configuration file.
		ERR_BACK_COMMAND_DISABLED = "§cThis command has been disabled by a server administrator."
		#
		# The message for when your latest death location could not be found.
		ERR_DEATH_LOC_NOT_FOUND = "§cCould not find your latest death position!"
		#
		# The message for when you are being teleported to your latest death
		DEATH_BEING_TELEPORTED = "§6Teleporting you to your §clatest death §6position..."
		#
		# The message for when you are teleported to your latest death
		DEATH_TELEPORTED = "§6You have been teleported!"

	["TPA++ Messages"."/tpadeny"]
		#
		# The message that is sent to the player who executes /tpadeny
		# Placeholders: "%s": "The senders name who got denied"
		RECEIVER_DENIES_TPA = "§6Denied teleport request from §c%s"
		#
		# The message that is sent to the sender when the receiver of their request executes /tpadeny
		# Placeholders: "%s": "The receiver's name who denied the TPA"
		SENDER_GOT_DENIED_TPA = "§6Your teleport request for §c%s §6was denied!"

	["TPA++ Messages"."/tpacancel"]
		#
		# The message that is sent to the player who executes /tpacancel
		# Placeholders: "%s": "The receiver's name who the sender cancelled the TPA request for"
		SENDER_CANCELS_TPA = "§6Cancelled teleport request for §c%s"
		#
		# The message that is sent to the receiver when the sender executs /tpacancel
		# Placeholders: "%s": "The sender's name who cancelled the request"
		RECEIVER_GOT_CANCELLED_TPA = "§6Your teleport request from §c%s §6was cancelled!"

	["TPA++ Messages"."/tpaaccept"]
		#
		# The message that is sent to the player who executes /tpaaccept
		# Placeholders: "%s": "The sender's name who sent the request"
		RECEIVER_ACCEPTS_TPA = "§6Accepted teleport request from §c%s"
		#
		# The message that is sent to the sender of the TPA request, when their TPA request is accepted
		# Placeholders: "%s": "The receiver's name who accepted the request"
		SENDER_GOT_ACCEPTED_TPA = "§6Your teleport request for §c%s §6was accepted!"

	["TPA++ Messages"."/tpa"]
		#
		# The message that is sent to the player that executes /tpa
		# Placeholders: "%s": "The receiver's name who got sent the TPA request"
		SENDER_SENT_TPA = "§6Successfully sent teleport request to §c%s"
		#
		# The message that is sent to the receiver of a TPA request
		# Placeholders: "%s": "The sender's name who sent the TPA request"
		RECEIVER_GOT_TPA = "§c%s §6wants to teleport to you!"

	["TPA++ Messages"."/tpahere"]
		#
		# The message that is sent to the player that executes /tpahere
		# Placeholders: "%s": "The receiver's name who got sent the TPAHERE request"
		SENDER_SENT_TPAHERE = "§6Successfully sent teleport §chere §6request to §c%s"
		#
		# The message that is sent to the receiver of a TPAHERE request
		# Placeholders: "%s": "The sender's name who sent the TPAHERE request"
		RECEIVER_GOT_TPAHERE = "§c%s §6wants §cyou §6to teleport to §cthem!"

	["TPA++ Messages"."/tptoggle"]
		#
		# The message that is sent to the player that executes /tptoggle, when their tptoggle is enabled
		TPTOGGLE_ENABLED = "§6You are §cnow §6automatically §cdenying §6outside §cteleport requests§6!"
		#
		# The message that is sent to the player that executes /tptoggle, when their tptoggle is disabled
		TPTOGGLE_DISABLED = "§6You are §cno longer §6automatically §cdenying §6outside §cteleport requests§6!"

	["TPA++ Messages"."/tpblock"]
		#
		# The message that is sent to the player that executes /tpblock, when they attempt to block themselves
		CANNOT_BLOCK_SELF = "§6You §ccannot §6block §cyourself§6!"
		#
		# The message that is sent to the player that executes /tpblock, when they attempt to block a player whom they have already blocked
		# Placeholders: "${blocked_player}": "The player who has already been blocked"
		ALREADY_BLOCKED_PLAYER = "§6You have §calready §6blocked §c${blocked_player}§6!"
		#
		# The message that is sent to the player that executes /tpblock, when their block was successful
		# Placeholders: "${blocked_player}": "The player who was unblocked"
		SENDER_BLOCKED_PLAYER = "§6Successfully blocked §c${blocked_player}§6!"
		#
		# The message that is sent to the player that was blocked by the sender
		# This has no affect when it is disabled in the config.
		# Placeholders: "${sender_name}": "The player who blocked the recipient"
		PLAYER_BLOCKED_BY_SENDER = "§6You have been §cblocked §6by §c${sender_name}§6!"

	["TPA++ Messages"."/tpunblock Messages"]
		#
		# The message that is sent to the player that executes /tpunblock, when they attempt to unblock themselves
		CANNOT_UNBLOCK_SELF = "§6You §ccannot §6unblock §cyourself§6!"
		#
		# The message that is sent to the player that executes /tpunblock, when they attempt to unblock a player whom they have not already blocked
		# Placeholders: "${blocked_player}": "The player who hasn't been blocked"
		HAVENT_BLOCKED_PLAYER = "§6You §chaven't §6blocked §c${blocked_player}"
		#
		# The message that is sent to the player that executes /tpunblock, when their unblock was successful
		# Placeholders: "${unblocked_player}": "The player who was unblocked"
		SENDER_UNBLOCKED_PLAYER = "§6Successfully unblocked §c${unblocked_player}§6!"
		#
		# The message that is sent to the player that was unblocked by the sender
		# This has no affect when it is disabled in the config.
		# Placeholders: "${sender_name}": "The player who blocked the recipient"
		PLAYER_UNBLOCKED_BY_SENDER = "§6You have been §cunblocked §6by §c${sender_name}§6!"

	["TPA++ Messages"."TPA Request Timeout"]
		#
		# The message that is sent to the sender of a TPAHERE request, when their TPAHERE request expires
		# Placeholders: "%s": "The receiver's name who was sent the TPAHERE request"
		SENDER_TPA_TIMEOUT = "§6Your teleport §chere §6request to §c%s §6timed out!"
		#
		# The message that is sent to the receiver of a TPAHERE request, when their TPAHERE request expires
		# Placeholders: "%s": "The sender's name who sent the receiver the TPAHERE request"
		RECEIVER_TPA_TIMEOUT = "§6Your teleport §chere §6request from §c%s §6timed out!"

	["TPA++ Messages".Limitations]
		#
		# The message displayed when the player accepting or sending a TPA request, is too far away.
		# Placeholders: "${distance}": "The distance between the two players."
		#     "${expectedDistance}": "The maximum distance players can be from eachother to teleport"
		ERR_TOO_FAR_EXECUTOR = "§cYou are too far! You are ${distance} blocks apart!\n§cYou must be a maximum of ${expectedDistance} blocks apart!"
		#
		# The message displayed to the other player, when the TPA request is too far away
		# Placeholders: "${distance}": "The distance between the two players."
		#     "${expectedDistance}": "The maximum distance players can be from eachother to teleport"
		#     "${otherPlayerName}": "The name of the executor."
		ERR_TOO_FAR_OTHER_PLAYER = "§c${otherPlayerName} failed to teleport: You are too far! You are ${distance} blocks apart!\n§cYou must be a maximum of ${expectedDistance} blocks apart!"
		#
		# The message displayed when the player accepting or sending a TPA request, is too close.
		# Placeholders: "${distance}": "The distance between the two players."
		#     "${expectedDistance}": "The minimum distance players can be from eachother to teleport"
		ERR_TOO_CLOSE_EXECUTOR = "§cYou are too close! You are ${distance} blocks apart!\n§cYou must be a minimum of ${expectedDistance} blocks apart!"
		#
		# The message displayed to the other player, when the TPA request is too close.
		# Placeholders: "${distance}": "The distance between the two players."
		#     "${expectedDistance}": "The minimum distance players can be from eachother to teleport"
		ERR_TOO_CLOSE_OTHER_PLAYER = "§c${otherPlayerName} failed to teleport: You are too close! You are ${distance} blocks apart!\n§cYou must be a minimum of ${expectedDistance} blocks apart!"
		#
		# The message displayed to the other player, when the TPA request is from another dimension.
		# Placeholders: "${executorDimension}": "The name of the dimension the executor is in"
		#     "${otherPlayerDimension": "The name of the dimension the other player is in"
		ERR_DIFFERENT_DIMENSIONS_EXECUTOR = "§cYou must be in the same dimension!\n§cYou are in: ${otherPlayerDimension}\n§cThey are in: ${executorDimension}"

	["TPA++ Messages"."/tpaplusplus"]
		#
		# The message displayed when someone enters /tpaplusplus version
		# Placeholders: "%s": "The version the mod is running"
		TPAPLUSPLUS_VERSION = "§6You are running TPAPlusPlus version §c%s"
		#
		# The first message displayed when someone enters /tpaplusplus reload config -force
		TPAPLUSPLUS_FORCE_RELOADING_CONFIG = "§6Reloading §cConfiguration§6 and wiping old data (TPA request's, death locations)..."
		#
		# The second message displayed when someone enters /tpaplusplus reload config -force
		TPAPLUSPLUS_FORCE_RELOADED_CONFIG = "§6Finished Reloading Configuration and wiping data!"
		#
		# The first message displayed when someone enters /tpaplusplus reload config
		TPAPLUSPLUS_RELOADING_CONFIG = "§6Reloading §cConfiguration§6..."
		#
		# The second message displayed when someone enters /tpaplusplus reload config
		TPAPLUSPLUS_RELOADED_CONFIG = "§6Finished Reloading Configuration!"
		#
		# The message displayed when someone runs "/tpaplusplus refactor colors" with not enough colors specified
		#Placeholders: "%s": "The amount of colours that the player entered."
		ERR_TPAPLUSPLUS_COLORS_REQUIRE_SIX_COLORS = "§cIllegal Arguments! Required 6 colors, you entered: %s"
		#
		# The message displayed when someone runs "/tpaplusplus refactor colors" when the primary and secondary colours are the same
		ERR_TPAPLUSPLUS_COLORS_CANNOT_BE_THE_SAME = "§cThe primary and secondary colours cannot be the same!"
		#
		# The message displayed when someone runs "/tpaplusplus refactor colors" with invalid colour codes
		#Placeholders: "%s": "The string the user entered instead of a valid colour code."
		ERR_TPAPLUSPLUS_COLORS_INVALID_COLORS = "§cIllegal Arguments! Requires a valid Minecraft chat colour code, you entered: %s"
		#
		# The second message displayed when someone runs "/tpaplusplus refactor colors" with invalid colour codes
		#Placeholders: "%s": "A random valid colour code"
		ERR_TPAPLUSPLUS_COLORS_INVALID_COLORS_EXAMPLES = "§cExamples: %s, %s, %s, %s, %s, %s"
		#
		# The message displayed when someone runs "/tpaplusplus refactor colors" successfully!
		TPAPLUSPLUS_COLORS_SUCCESS = "§6Successfully §creformatted §6your messages! Your §ccolor-set §6has been §cmodified§6!"

	["TPA++ Messages".Windups]
		#
		# The message displayed during a windup for a command when it has been enabled in the config
		#Placeholders: "${time}": "How much time is remaining."
		COUNTDOWN_TIME_REMAINING = "§c${time}§6..."
		#
		# The message displayed during a windup for a command when the player moves further than the allowed distance in the config
		#Placeholders: "${command_used}": "The command that the player tried to execute, but they moved too far. This placeholder respects the command names set in the config."
		PLAYER_MOVED_DURING_WINDUP = "§cYou moved too much whilst trying to execute ${command_used}, so it was cancelled."

	["TPA++ Messages".Cooldowns]
		#
		# The message displayed when a player tries to execute a command but it is currently on cooldown.
		#Placeholders: "${command_used}": "The command that was on cooldown. This placeholder respects the command names set in the config."
		#              "${time_remaining}": "How long is left on the cooldown (in seconds)"
		COMMAND_ON_COOLDOWN_MESSAGE = "§6\"§c/${command_used}§6\" §cis currently on §ccooldown§6, please wait §c${time_remaining}§6s!"
		#
		# The message displayed when a player tries to execute a command, but they are currently on cooldown.
		#Placeholders: "${time_remaining}": "How long is left on the cooldown (in seconds)"
		PLAYER_ON_GLOBAL_COOLDOWN_MESSAGE = "§cYou §6are currently on §ccooldown§6, please wait §c${time_remaining}§6s before running another command!"

