
["TPA++ Configuration"]
	# Unlike the messages configuration, nearly every value in this config can be changed and reloaded safely during runtime!
	# How long until teleport requests expire (in seconds)
	# The default is 60 seconds ( 1 minute ), if you wish to disable this set this to 0
	#Range: > 0
	"TPA Timeout" = 60
	#
	# How long it takes until a player is teleported via /tpaaccept
	# The default is 5 seconds, if you wish to disable this set this to 0
	#Range: > 0
	"TPA Accept Time" = 5
	#
	# Whether or not the /back system is enabled.
	# /back is the command that will teleport you to your latest death!
	"Use /back" = true
	#
	# Whether to allow players with /tptoggle enabled, to send a teleport request
	"Allow TPToggled Players To Send Requests" = false
	#
	# Whether to send a message to the person being blocked / unblocked, when the sender blocks them.
	"Send Blocked Messages To Both Players" = true

	["TPA++ Configuration".Commands]
		# This section of the config allows you to change the commands to whatever you please!
		# For example, you can change the /tpa command to /teleport-request, which means instead of entering /tpa players will have to enter /teleport-request
		# Command aliases (running the same command with one or more commands, for example you can make /tpa, /teleport-request and /tpasend all run the same command ( /tpa )
		# It is NOT recommended to use anything other than ASCII characters here!
		# Modifying any of these commands requires a restart to take effect.
		#
		# The name of the /tpa command (what players run in chat)
		TPA_COMMAND_NAME = "tpa"
		#
		# The name of the /tpahere command (what players run in chat)
		TPAHERE_COMMAND_NAME = "tpahere"
		#
		# The name of the /tpaaccept command (what players run in chat)
		TPAACCEPT_COMMAND_NAME = "tpaaccept"
		#
		# The name of the /tpadeny command (what players run in chat)
		TPADENY_COMMAND_NAME = "tpadeny"
		#
		# The name of the /tpacancel command (what players run in chat)
		TPACANCEL_COMMAND_NAME = "tpacancel"
		#
		# The name of the /tptoggle command (what players run in chat)
		TPTOGGLE_COMMAND_NAME = "tptoggle"
		#
		# The name of the /tpblock command (what players run in chat)
		TPBLOCK_COMMAND_NAME = "tpblock"
		#
		# The name of the /tpunblock command (what players run in chat)
		TPUNBLOCK_COMMAND_NAME = "tpunblock"
		#
		# The name of the /back command
		# This has no affect if /back is not enabled in the configuration file.
		BACK_COMMAND_NAME = "back"

	["TPA++ Configuration".Limitations]
		# All limitations are DISABLED by default.
		#
		# How far away a player can be from another player in order to teleport
		# Set this to 0 if you wish to disable this limitation
		#Range: 0.0 ~ 1.7976931348623157E308
		"Furthest Allowed Teleport Distance" = 0.0
		#
		# How close a player can be from another player in order to teleport
		# Set this to 0 if you wish to disable this limitation
		#Range: 0.0 ~ 1.7976931348623157E308
		"Closest Allowed Teleport Distance" = 0.0
		#
		# Whether to allow sending TPA requests if the player(s) are not in the same dimension
		# Set this to false if you wish to disable this limitation
		"Allow Inter-Dimensional Teleport" = true
		#
		# Whether to disable the range checks feature when teleporting inter-dimensionally
		# This has no affect if "Allow Inter-Dimensional Teleport" is false, or if all range checks are disabled.
		# TPAPlusPlus will automatically account for the nether's coordinate system ( 1 block in the nether is 8 blocks in the overworld! )
		# Set this to false if you wish to disable this limitation
		"Disable Inter Dimensional Range Checks" = true

	["TPA++ Configuration".Windups]

		["TPA++ Configuration".Windups.Delay]
			# This section of the config controls how long things like commands take to execute.
			# This is measured in seconds.
			# These values support three decimal places of precision (For example, you can enter 1.5 or 10.375, but not 20.1234 (it will still work, just anything after the 3rd decimal place will be discarded)).
			# Set this to 0 if you wish to disable the countdown
			#
			# How long it takes for players to run /back.
			#Range: 0.0 ~ 2.147483647E9
			"Back Windup" = 0.0
			#
			# How long it takes for players to run /tpaaccept.
			#Range: 0.0 ~ 2.147483647E9
			"Accept Windup" = 0.0
			#
			# How long it takes for players to run /tpadeny.
			#Range: 0.0 ~ 2.147483647E9
			"Deny Windup" = 0.0
			#
			# How long it takes for players to run /tpacancel.
			#Range: 0.0 ~ 2.147483647E9
			"Cancel Windup" = 0.0
			#
			# How long it takes for players to run /tpa
			#Range: 0.0 ~ 2.147483647E9
			"TPA Windup" = 0.0
			#
			# How long it takes for players to run /tpahere
			#Range: 0.0 ~ 2.147483647E9
			"TPAHere Windup" = 0.0
			#
			# How long it takes for players to run /tptoggle.
			#Range: 0.0 ~ 2.147483647E9
			"Toggle Windup" = 0.0
			#
			# How long it takes for players to run /tpblock.
			#Range: 0.0 ~ 2.147483647E9
			"Block Windup" = 0.0
			#
			# How long it takes for players to run /tpunblock.
			#Range: 0.0 ~ 2.147483647E9
			"Unblock Windup" = 0.0
			#
			# The threshold before a message is sent to the player with the delay, this value ranges from 0 - 1 because this represents the number after the decimal place.
			# Okay that probably made no sense, so here's an example:
			# Say you have the /tpa windup set to 3.75. Then you have this set to 0.5. Since 0.75 (/tpa windup without the whole number) is GREATER than 0.5, when the player first enters the command, a message will show up saying 3.75 seconds remaining.
			# But now lets say the /tpahere windup is set to 1.25. Since 0.25 (again the /tpahere windup without the whole number) is LESS than 0.5, no message will be sent to the player, and the countdown will just continue on with 3.. 2.. 1.. etc.
			# If this is set to 1, no messages will be displayed. If this is set to 0, ALL messages will be displayed.
			# This has no effect on the countdown after the initial command.
			#Range: 0.0 ~ 1.0
			"Windup Decimal Message Threshold" = 0.0

		["TPA++ Configuration".Windups.Distance]
			# This section of the config controls how far away people can be, from the position that they executed each command.
			# This is measured in blocks.
			# Set this to 0 if you want players to not be able to move at all during a countdown, or to -1 to completely disable this feature and allow them to move around freely during a windup.
			# WARNING: SETTING THESE VALUES IN-BETWEEN 0 AND -1 WILL CAUSE THEIR RESPECTIVE COMMAND TO BE UNUSABLE.
			#
			# How far away players can be from the position where they ran /back.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Back Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpaaccept.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Accept Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpadeny.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Deny Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpacancel.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Cancel Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpa.
			#Range: -1.0 ~ 1.7976931348623157E308
			"TPA Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpahere.
			#Range: -1.0 ~ 1.7976931348623157E308
			"TPAHere Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tptoggle.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Toggle Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpblock.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Block Windup Distance" = 0.0
			#
			# How far away players can be from the position where they ran /tpunblock.
			#Range: -1.0 ~ 1.7976931348623157E308
			"Unblock Windup Distance" = 0.0

	["TPA++ Configuration".Cooldowns]
		# This section of the config controls the cooldown (how long the player must wait) after a command executes.
		# This is measured in seconds.
		# Set this to 0 if you wish to disable the cooldown
		#
		# How long it takes for players to run /back.
		#Range: > 0
		"Back Cooldown" = 0
		#
		# How long it takes for players to run /tpaaccept.
		#Range: > 0
		"Accept Cooldown" = 0
		#
		# How long it takes for players to run /tpadeny.
		#Range: > 0
		"Deny Cooldown" = 0
		#
		# How long it takes for players to run /tpacancel.
		#Range: > 0
		"Cancel Cooldown" = 0
		#
		# How long it takes for players to run /tpa.
		#Range: > 0
		"TPA Cooldown" = 0
		#
		# How long it takes for players to run /tpahere.
		#Range: > 0
		"TPAHere Cooldown" = 0
		#
		# How long it takes for players to run /tptoggle.
		#Range: > 0
		"Toggle Cooldown" = 0
		#
		# How long it takes for players to run /tpblock.
		#Range: > 0
		"Block Cooldown" = 0
		#
		# How long it takes for players to run /tpunblock.
		#Range: > 0
		"Unblock Cooldown" = 0
		#
		# The delay after a command is executed, before another one can be run.
		#Range: > 0
		"Global Cooldown" = 0

	["TPA++ Configuration"."Advanced Settings"]
		#
		# WARNING: These options are related to asynchronous operations and/or saving / loading datain . Modifying these from the defaults has a small chance to corrupt data.
		# WARNING: It is only recommended to change these values from their defaults if you know how they work internally UNLESS explicitly said so in the option you are trying to modify.
		# Most options here have already been optimized for most systems, I doubt you will experience significant performance gains by changing the options below, unless you have an insane amount of players connected, in that case boosting the thread counts should help a bit.
		# Modifying these options may require a restart of the game.
		#
		# How long (in seconds) between autosaves, if you experience data loss, set this number lower.
		#Range: > 1
		AUTOSAVE_INTERVAL = 300
		#
		# How often to automatically check for updates in the background.
		# This will send a network request to Modrinth's API based off this interval, and tell you if you are running a version of TPA++ that is out of date.
		# Alternatively, you can check for updates manually by running /tpaplusplus version (this setting does not affect manual update checking).
		# This value is measured in minutes, and setting it to 0 will disable update checking.
		# Modifying this value requires a restart of the game.
		#Range: 0 ~ 153722867280911
		CHECK_FOR_UPDATES_INTERVAL = 60
		#
		# Whether to use an async tick loop for TPA++, that runs alongside the main thread.
		# Operations that run synchronously with the main thread, are usually extremely inexpensive to run.
		# Only enable this if you have an insane amount of players, or you have noticed performance problems with running it synchronously.
		# Modifying this value requires a restart of the game.
		USE_NON_BLOCKING_ASYNC_TICK_LOOP = true
		#
		# How often (per second) to update the tick loop. Changing this value will NOT make the game tick run faster, it will only make TPA++ more sensitive and responsive to things (since it will be updated faster).
		# For example, a value of 20 will cause TPA++ to update 20 times a second (this is also Minecraft's Tick Rate).
		# It is completely okay to lower this value, even to something low like 4 if you have a lot of players.
		# Modifying this value requires a restart of the game.
		#Range: > 1
		ASYNC_TICK_LOOP_UPDATE_RATE = 20

