
[svmm-player-ecfd61e7-a890-3976-a776-32a4fcb10c86]

	[svmm-player-ecfd61e7-a890-3976-a776-32a4fcb10c86.self-config]
		#Condition for when the mod is triggered
		#Allowed Values: SHIFT_HELD, SHIFT_NOT_HELD, ALWAYS
		trigger_when = "SHIFT_NOT_HELD"

	[svmm-player-ecfd61e7-a890-3976-a776-32a4fcb10c86.toggles]
		#Whether or not the player disabled the mod for themselves
		mod_disabled = false
		#Whether or not the player disabled giant vein mining for themselves
		giant_vein_mining_disabled = true

	[svmm-player-ecfd61e7-a890-3976-a776-32a4fcb10c86.restrictions]
		#Whether or not the mod was restricted by an operator
		mod_restricted = false
		#Whether or not giant vein mining was restricted by an operator
		giant_vein_mining_restricted = false
		#Whether or not tunneling was restricted by an operator
		tunneling_restricted = false
		#Whether or not /svmm force was restricted by an operator
		force_restricted = true

